### ISSUE TITLE
Curl from readme responds with LFS fileinfo

### ISSUE THREAD

**Issue by craigjmidwinter** [CloudDefenseAI/cd#5]
I noticed some previously working pipelines failing today. Upon investigation, it looks like the url to the tarball (at least the linux one) now responds with git-lfs info (a spec version, SHA and size). Maybe the latest release exceeds a file size limit of some sort?

**Comment by abhiv** [comment]
@craigjmidwinter thank you for filing the issue, yeah seems like git-lfs is for binaries above 50MB, and instead of an actual tar file git actually stores the pointer to git-lfs. Let me look into it. Do you update the binary every time you run the pipeline or did you manually pull the latest release?

**Comment by craigjmidwinter** [comment]
It looks like it's pulling the binary every pipeline run on the repos that I'm currently investigating, and I just manually tried pulling during troubleshooting

**Comment by abhiv** [comment]
@craigjmidwinter Yeah I actually figured that after I asked the question. I've forced pushed the non-lfs (actual) files and removed the lfs related configs, I think we didn't anticipate that pipelines would be impacted by this. I think we'll have to rethink how we optimize the binary releases.

**Comment by abhiv** [comment]
The url https://raw.githubusercontent.com/CloudDefenseAI/cd/master/latest/cd-latest-mac-x64.tar.gz (and other OS-es) are now direct files instead of metadata. Sorry for the inconvenience @craigjmidwinter

**Comment by craigjmidwinter** [comment]
Awesome! Thanks!
